### ISSUE TITLE
latexmls does not work reliable

### ISSUE THREAD

**Issue by cmaeder** [KWARC/sTeX#107]
In https://github.com/KWARC/MMT/issues/29 I've reported that building all of smglom took 20 hours.
After the weekend I've found (the process) `latexmls` running for over a day without any progress.
(I've no clue how to reproduce this, though.)

**Comment by cmaeder** [comment]
It seems that the timeout (given by `--expire=10`) was not respected in one case (or maybe another latexmls instance existed without timeout for some other reason).

**Comment by dginev** [comment]
Keep in mind there are two timeouts:
 * ```--expire=X``` will shutdown latexmls if no job arrives in X seconds, 0 will keep it on until externally killed
 * ```--timeout=X``` will timeout the conversion process internally, without killing latexmls/latexmlc, so that you can set upper bounds to the TeX conversion.

If you think you're seeing a bug with their function, try to obtain a self-contained example, then I'll be happy to take a look and patch it.

**Comment by cmaeder** [comment]
I don't use the `--timeout=...` option of latexml (so the default of 600 will be used).

However, I use a separate timeout for the java process that calls `latexmlc` to ensure no "hanging".
