### ISSUE TITLE
nobrackets does not work for \prefix

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#128]
```\prefix``` and ```\postfix``` did not accept the ```nobrackets``` attribute. I copied the code over from the ```mi``` keygroup (in ```presentation.dtx```), but the brackets do not work correctly yet. See the ```\minval``` test in ```MathHub/smglom/numberfields/source/minmax.tex```. We need to look at this soon.

**Comment by La-Stravaganza** [comment]
Sorry for being unproductive recently. Could you illustrate more about this ticket?

**Comment by La-Stravaganza** [comment]
I tried to understand why ``\mixfixi`` can works correctly, I think the key part for solving this problem is to implement a similar checker as ``\PresWrite`` in ``\prefix``.

``\mixfix`` is implemented as this:
```latex
\def\PrecWrite#1{\ifnum\pres@p>\pres@current@precedence\else{#1}\fi}

\newcommand\mixfixi[4][]%key, pre, arg, post
{%
	\clearkeys\setkeys{mi}{#1}\prep@keys@mi%
	\PrecWrite\pres@lbrack%
	#2{\edef\pres@current@precedence{\pres@pi}#3}#4%
	\PrecWrite\pres@rbrack
}%
```

As we can see, before writing brackets, ``\mixfix`` will try to compare the precedences and determine when to write a bracket. 

But in the definition of ``\prefix``, there's no similar mechanism. As a result, brackets will be printed anyway, ``nobrackets`` option won't work.
```latex
\newcommand\prefix[3][]%key, fn, arg
{%
	\prepost@clearkeys%
	\setkeys{prepost}{#1}%
	{#2}\pres@lbrack{\edef\pres@current@precedence{\pres@pi@key}#3}\pres@rbrack%
}
```

Now I have two possible solutions:

1. The most simple idea is, that we deal with infinite precedence separately. If ``\prefix`` detects current precedence is infinite, then it doesn't print the brackets

2. We change the precedence logic behind ``\prefix``. I noticed, in ``minmax.tex``
```latex
  \symdef[bvars=1,bargs=2]{bminval}[3]{\prefix[p=900]{\minvalFN_{\withprecii\niprec{#2}}}{#3}}
  \symtest{bminval}{\bminval{i}{i\in\mathbb{N}}{1/i}}
```
will generate 
![selection_010](https://cloud.githubusercontent.com/assets/10081485/10337730/0b8d596c-6d02-11e5-8b54-d0a5a211fdbe.png)

I am not sure the brackets around ``1/i`` is necessary or not. I feel that they are probably unnecessary, since in this case there's only one precedence, no matter ``p=900`` or ``p=1000000``, it should behave consistently.
