### ISSUE TITLE
stex2html package design 

### ISSUE THREAD

**Issue by angerhang** [KWARC/sTeX#135]
Instead of having `stex-ns` package which only registers the namespaces for HTML branch, I think it is better to have a `stex2html.[sty.ltxml|styl]` package which mostly does the same thing as `stex-ns.[sty.ltxml|sty]`, but also sets the schema to `ltxml+omdoc.rnc`. 

Hence, we can get rid of the `html` option for html branch at the same time. Now, one can generate HTML from sTeX by merely including `stex2html` package, which makes everything much easier.  

@kohlhase maybe you can comment on this? (see the details in 54d85090ec01f9ab9c6b18d2c2078991530516ae)

**Comment by dginev** [comment]
FYI the LaTeXML way to distinguish formats would be via:

``` --format=html5 ```

or 

``` --format=omdoc ```

Which used to be responsible for changing the stylesheet, but with the upcoming improvements in 0.8.3 (ETA early 2016) you could have an entire format-based profile, allowing to select or deselect various post-processors. @brucemiller we could think of helping the sTeX effort in migrating to this scheme?

The theoretically clean setup, which however costs development time and understanding of the math post-processors, is to create only XMath mathematics in the sTeX bindings, while improving the PMML and OpenMath post-processors for LaTeXML to the point where you can generate the exact mathematical markup wanted.

But that requires good sync between @kohlhase  and @brucemiller, e.g. to get the best workflow for binders etc.

**Comment by angerhang** [comment]
After a discussion with Michael this week, we think using LaTeXML to distinguish the format-based profile is a better approach.

Currently sTeX is switching over to CMML, so I think instead of improving the PMML and OpenMath post-processors, what is more needed is to improve the CMML and PMML post-processors right?

However, if sTeX is only producing XMath, does it matter at all that which markup for math we use?

**Comment by dginev** [comment]
You only need to improve the post-processors when they are not good enough - so that should happen incrementally, as you have examples of undesired markup.

Also, sTeX produced a lot of hand-crafted OpenMath when I was working on it, notably related to binders and associative arguments. It is rather unclear what the correct XMath equivalent would be for that, and you would most likely need to walk @brucemiller through the concrete matematical formulas and the way you want to see them converted, to make sure the post-processors are aware of these uses.

The simple switch to CMML would simply imply rewriting these OpenMath-creating DefConstructors into CMML-creating ones, which I think was done some time back.

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#38
