### ISSUE TITLE
regression testing for sTeX. 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#193]
The incident around #190 shows us that we need a regression testing mechanism for sTeX. We had a glaring problem and did not discover it for more than 4 months. Disconcerting. Here is the plan 
1. set up travis for sTeX (done by Christian). 
2. develop a reasonable-coverage collection of MathHub content and its "intended results"
3. do the same for a non-MathHub collection. 
4. collect some specific "unit" tests
5. make tests from that and enable them in travis. 
For 2. I want to use the MathHub library "HelloWorld" (see https://gl.mathhub.info/groups/HelloWorld) and for 3. I wan to use the ```examples``` directory in the sTeX distribution. For 4. Deyan said he had tests in http://github.com/KWARC/LaTeXML. 
@dginev @m-iancu @angerhang @cmaeder please give me feedback (and help).

**Comment by dginev** [comment]
Here is my ideal workflow, from a very myopic LaTeXML ecosystem perspective, which you can adapt to a MathHub-compatible flow.

LaTeXML now supports plugins, and an example of a successful KWARC plugin that has been used for a long while are [the bindings for MathWebSearch](https://github.com/KWARC/LaTeXML-Plugin-MathWebSearch).

That tiny example of a plugin for MWS also has a single [regression test](https://github.com/KWARC/LaTeXML-Plugin-MathWebSearch/blob/master/t/1_contentquery.t) to provide some minimal level of sanity.

From LaTeXML's perspective, the sTeX bindings could fit wonderfully as a plugin, which can bundle its own test suite (as opposed to modifying the core LaTeXML installation and maintaining a separate fork).

Plugins are also trivial to install, as they leverage Perl's package distribution ecosystem and can be installed e.g. via ```cpanm LaTeXML-Plugin-sTeX```, which also runs the test suite by default. An extra benefit is that the plugin maintains version sanity in its Makefile.PL specification, so that a certain version of sTeX can specify the exact version of LaTeXML it requires to be operational. The current CTAN distribution of the sTeX bindings for LaTeXML is more a nuisance in my workflow than a benefit, as I need to explicitly disable them when developing. The debian package versions of latexml and stex are bound to be out of sync, which means they are unusable together. Maybe you know of a user who managed to run the sTeX -> OMDoc workflow from his debian package installation, but I would be shocked if they existed.

As to the tests themselves, the LaTeXML regression tests are a good example to follow - if every core feature of sTeX has a minimal TeX example with the corresponding OMDoc, changes would trigger errors in the test suite. The downside is that there is extra maintenance work, as the test suite will need to be updated every time the markup spec changes.

The (probably outdated) test I had until now is at the KWARC fork of LaTeXML - you can find it [here](https://github.com/KWARC/LaTeXML/tree/master/t/daemon/profiles/stex)

**Comment by dginev** [comment]
We could try to move the entire KWARC fork of LaTeXML to the same plugin as the sTeX bindings, which would also simplify the current need to periodically reintegrate the master LaTeXML with the KWARC fork. For that we would need to work with Bruce to transfer all sTeX-required modifications of LaTeXML to master, which is easier said than done. Plugins can't override core LaTeXML files.

**Comment by kohlhase** [comment]
Let me give you what I have been thinking; and I think this is independent of the plugin idea, which sounds appealing -- prossibly because I do not quite understand what it entails. 

Rather than having lots of small tests I was thinking of the two bigger (but still somewhat minimal) test suites that I was mentioning above. Here is the workflow I envision 
1. on every commit to the sTeX repository, travis builds HelloWorld /examples and compares the results to a dedicated results tree (they are in the two repositories).
2. If these are the same, then all is fine. If there is a difference the committer and the sTeX maintainer get notified and look at the differences. 
3. If the changes are legitimate/intended, then we commit them, and they become the new gold standard, if not, we fix the sTeX bindings. 
Given that the test cases cover enough of sTeX, this should also be safe, but more easily maintained. But of course, 3. needs to be done conscientiously.

**Comment by kohlhase** [comment]
Now let me come to the plugin idea, and see what would be involved in this. Correct me where I am wrong. I would 
1. move all the existing *.ltxml files from sTeX to the plugin repos and commit them there, probably conserving the directory organization. 
2. add lots of comments (actually, possibly extract comments from the DTX files)
3. remove all the ltxml from the DTX files in the sTeX distribution, which would thereby become LaTeX-only and the *.ltxml files would disappear from TeXLive (eventually). 
4. you (or @angerhang) would make the plugin wrapper, and you would work with Bruce on eliminating the KWARC branch (which I agree would be a good thing). 

What worries me is the more difficult synchronization between the packges, classes and bindings, but I guess we can organize that by keeping corresponding (feature) branches and crossref issues between the sTeX and sTeX-plugin repositories (after all they are all on GitHub).

**Comment by dginev** [comment]
Sounds exactly right. And I don't have a strong opinion whether many small tests are better or worse than 1 or 2 larger ones, as long as they cover all essentials.

Btw the best way to keep the LaTeX and Perl coverage the same would be to try both against the same test suite, and Travis can validate that both pdflatex and latexml are completing error-free (though I am not sure if PDF diff is a sensible thing to do).

**Comment by kohlhase** [comment]
> Btw the best way to keep the LaTeX and Perl coverage the same would be to try both against the same test suite,

yes, that was the plan. Of course, there is (as far as I know) no good way to compare two PDF files for "looking the same". Or at least I know of none. And what we would really need is a utility that compares the HTML generate from the OMDoc to see whether it looks the same as the PDF. Well, actually, we could generate derived versions from the PDF via pdf2ascii and html2ascii and compare them. That might actually be useful.

**Comment by kohlhase** [comment]
I am spinning some of the "support regression testing" functionality for MathHub into https://github.com/KWARC/MMT/issues/101 I will have to support something like that in Makefiles of the sTeX distribution for the sTeX distribution (see #194).

**Comment by kohlhase** [comment]
I am also spinning the plugin discussion off to #195, since it is independent of the disucssion here.

**Comment by kohlhase** [comment]
this seems essentially done.
