### ISSUE TITLE
selecting the ltxml+omdoc.rnc schema in html mode

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#25]
@dginev please comment. 

In the new approach described in #20 there is still a problem to be solved: If we want to generate OMDoc, we need set the schema ```omdoc+ltxml.rnc```  and if want to generate html, then we need ```ltxml+omdoc.rnc```. Actually (re)-setting the schema is no problem using ```RelaxNGSchema```, but we need to do it selectivelly, and I have a utility binding ```shtml.sty.ltxml``` (where should this go?) that does this. 

I imagine the sTeX setup in the following way: The HTML workflow is the default one, to you just use 
```
\usepackage{stex}
```
or a selected set of sTeX packages you need, and then just running LaTeXML over it generates html (currently, we need the ```insTeX.opt``` options for that; but maybe we can make the sTeX bindings part of the LaTeXML distribution, which would fix that). 

If you use 
```
\documentclass{omdoc}
``` 
or any derived class, then OMDoc is generated. I think we can just do that by making sure that ```omdoc.cls.ltxml``` sets the right ```RelaxNGSchema``` late enough (so that it does not get overwritten by the sTeX packages. 
Maybe we need a version ```ProvideRelaxNGSchema``` which does not overwrite for the packages. Then we could just use ```RelaxNGSchema``` in ```omdoc.cls.ltxml```.

**Comment by angerhang** [comment]
Based on the new HTML mode design, I would suggest a different approach, because we are no longer using the utility binding, but rather extending the existing bindings in `*.cls/sty.ltxml`s. 

Given a document with the preamble similar to the following:
```tex
\documentclass{article}
\usepackage[html]{omdoc}
\begin{document}
```
we can imagine sTeX by default being set as non-HTML mode and being switched to produce HTML when `html` is passed to `omdoc` package, in which case we can select [`ltxml+omdoc` as our schema](https://github.com/KWARC/sTeX/commit/8c4b6b78859018682452ddcc5add4c54fe69325a). 

In addition, whenever the `html` option is passed, `omdoc` also passes `html` option to other packages that have sTeX specific bindings to ensure the generated HTML has the right output.

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#46
