### ISSUE TITLE
Reinstate Indexing in \defi*, \adefi*, (and give them a new optional last argument)

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#61]
I have changed the call pattern from ```\defi[foo]{Foo}``` for a symbol with name ```foo``` and verbalization ```Foo``` to ```\defi[foo]{Foo}[<indexkeys>]```. On the pdflatex front, the newly defined definienda are passed to an index command, which takes the ```<indexcommand>``` keys. See the package documentation of ```statements``` for details. 

On the LaTeXML side, no indexing is done currently (I got rid of that in commit https://github.com/KWARC/sTeX/commit/0c7d3c307d788649fbefc4d18f7aa448588c22cd) because it mad some MMT parsing complicated. But I think we should get it back conditionally. I will make indexing conditional on the PDFLaTeX side and design a package option for that. @angerhang, you can use that to conditionally reinstate indexing. This should be done together with #59 and should land in a single pull request.

**Comment by kohlhase** [comment]
I have added the ```defindex``` package option to ```statements.sty``` (see the documentation there; it uses an internal switch to do the indexing in ```\*defi*```). You should do the same when adding the indexing back (i.e. only generate the indexing elements when the ```defindex``` option is set. But #62 needs to be done first (or with this).

**Comment by angerhang** [comment]
@dginev 
I struggled with how to make the defindex optional to have `DefConstructor` generating two different outputs. 

My original idea is to have 
```perl
DeclareOption('defindex', sub {AssignValue('@defindex', 1, 'global'); });
```
and retrieve the value in `DefConstructor`, and beforeConstruct and afterConstruct add the index back accordingly.

 Would this be the approach that you choose?

**Comment by angerhang** [comment]
@dginev 
In the ebb7ad8a5d81badbf1bed7e4f3a0450f06eec81e commit, I made `defindex` switch optional.

However it is rather verbose right now? So I only changed `adefi` and left out the rest, since it is not optimal yet.

Is there any better way to make DefConstructor conditional?

**Comment by angerhang** [comment]
I spent a few hours playing with the binding option in sTeX, but still can't make the option work the way we want. 

In 28097626e2373499b6ec534c9d7af7dd1d3c562d, (I know this commit has many duplicated code  : p but I will refactor soon) I tentatively made defi* and adefi* optional. The `defindex` option by default is false and will be toggled if the option is passed to the binding.

```perl
RawTeX('\newif\if@defindex\@defindexfalse');
# the switch is don't toggling defindex option
DeclareOption('defindex', sub{Digest('\@defindextrue'); });
```

Strangely after I added the option in the preamble, the option still fails. I tried adding the options in both `pre.en.tex` and `preamble.en.tex` in `lmh`. 

I think the `DeclareOption` command does its job, if we explicitly call `ExecuteOptions`, which leads to a desired output. 

If DeclareOption does toggle the value of `defindex`, I suppose the only reason that causes this problem is the way we pass the option to `LaTeXML` binding?

@dginev can you take a look here?

**Comment by dginev** [comment]
If you want to make this cleaner, instead of conditionally changing the definition of ```\defi``` in runtime, you should have a single fixed DefConstructor that defines it, and you should check the value of your defindex switch in the ```afterDigest``` clause of the constructor passing it on as a Whatsit property. (Hopefully it's still set there, you'll need to throw it up from beforeDigest otherwise, look for "from_module" in modules as an example),

Then the "replacement" that produces the final XML can check the value of the property to fill in the right markup.

In untested code, something like:
```perl
  DefConstructor('\defi[]{} OptionalKeyVals:DEF',
		 "?#defindex(<omdoc:idx><omdoc:idt>)()"
		 ."<omdoc:term role='definiendum' name='?#1(#1)(#2)' cd='#theory'>#2</omdoc:term>"
		 ."?#defindex(</omdoc:idt><omdoc:ide index='default'><omdoc:idp>#2</omdoc:idp></omdoc:ide></omdoc:idx>)()",
       afterDigest => sub {
          my ($stomach, $whatsit) = @_;
          $whatsit->setProperty('defindex', IfCondition(T_CS('\if@defindex')));
          # ... other stuff
      } 
```

**Comment by dginev** [comment]
You need to invoke ```ProcessOptions()``` in the module that declares the options, so that LaTeXML explicitly processes them. Grep around for examples of how that is used, it's also described in the manual: http://dlmf.nist.gov/LaTeXML/manual/modules/LaTeXML_Package.html#A3.I14.ix6

**Comment by angerhang** [comment]
Oddly I did have `ProcessOptions()` right after the declaration of the options. 

The exact code for option part is like this:
```perl
RawTeX('\newif\if@defindex\@defindexfalse');
DeclareOption('defindex', sub{Digest(T_CS('\@defindextrue'));});
DeclareOption('showmeta', sub{PassOptions('metakeys','sty',ToString(Digest(T_CS('\CurrentOption')))); });
DeclareOption(undef, sub{PassOptions('omdoc','sty',ToString(Digest(T_CS('\CurrentOption')))); });
# The handler of defindex only works when we execute it explicitly. 
# ExecuteOptions('defindex');
ProcessOptions();
RequirePackage('omtext');
RequirePackage('modules');
```

This is what I have in `pre.en.tex` in `localmh/MathHub/smglom/topology/lib/pre.en.tex`
```
\documentclass{smglom}
\input{localpaths}
\usepackage[utf8]{inputenc}
\usepackage[defindex]{statements}
\input{\MathHub{smglom/topology/lib/preamble}}
\begin{document}
```

**Comment by angerhang** [comment]
This is done.
