### ISSUE TITLE
Command documentation and standardization

### ISSUE THREAD

**Issue by La-Stravaganza** [KWARC/sTeX#64]
@kohlhase 

I asked Tianlin to do  two things:
* read blue notes and understand the important macros.
* read every module defined, understand it, at the meantime, document the commands. I think this document will be really important for further writers.

Two thoughts today:

The first one:

``\trefi`` system is really annoying, a writer has to know that:

    * it is already defined
    * where it is defined

This is not so nice, my initial thought is that we should build a dictionary.
So that, if we know ``sets`` is already defined, then use something like:

``\use{sets}`` will let the program check where it is defined can translate it into ``\trefi[set]{sets}``

The second one:

About command standardization, I understand that **easy to type** and **meaningful** are hard to get at the same time, I think we can separate commands into two groups:

1. commonly-used:

 For commonly-used command, we can make them as simple as possible. It is crazy to type  ``\multiplication`` every time, ``\mul`` or ``\times`` is better and won't get confused.

 ``\lethan`` and ``\lessthan`` are quite similar, and badly abbreviated. if ``\lethen`` means less or equal, I think ``\leq`` is better.

2. rarely-used:

  We should make them as meaningful as possible. For example, ``\nfundefeqli`` is not readable at all. Commands like this should be more meaningful.

**Comment by kohlhase** [comment]
On 12/04/15 20:37, Jinbo Zhang wrote:
>
> @kohlhase <https://github.com/kohlhase>
>
> I asked Tianlin to two things:
>
>   * read blue notes and understand the important macros.
>
good.
>
>   * read every module defined, understand it, at the meantime,
>     document the commands. I think this document will be really
>     important for further writers.
>
I am not sure what "document the commands" means. We are indepenently
working on documentation.
>
> Two thoughts today:
>
> The first one:
>
> |\trefi| system is really annoying, a writer has to know that:
>
> |* it is already defined
> * where it is defined|
|yes, that is so, but the value in the links is proportional to the
annoyance in making them. |
> |
> |
>
> This is not so nice, my initial thought is that we should build a
> dictionary.
> So that, if we know |sets| is already defined, then use something like:
>
> |\use{sets}| will let the program check where it is defined can
> translate it into |\trefi[set]{sets}|
>
|Yes, we are working on tool support for that, but not at the level of
LaTeX. You should speak to @cjucovschi about this. |
>
> The second one:
>
> About command standardization, I understand that *easy to type* and
> *meaningful* are hard to get at the same time,
>
I have the feeling that you should be more precise here when you say
commands.  You should speak of "sTeX macros" for the command sequences
defined by the sTeX packages and classes and of "semantic macros" for
the macros defined by \symdef in the glossary. I guess you are talking
about the latter here.
>
> I think we can separate commands into two groups:
>
>  1. commonly-used:
>
> For commonly-used command, we can make them as simple as possible. It
> is crazy to type |\multiplication| every time, |\mul| or |\times| is
> better and won't get confused.
>
> |\lethan| and |\lessthan| are quite similar, and badly abbreviated. if
> |\lethen| means less or equal, I think |\leq| is better.
>
>  1. rarely-used:
>
> We should make them as meaningful as possible. For example,
> |\nfundefeqli| is not readable at all. Commands like this should be
> more meaningful.
>
I agree with your sentiment here, but alas it is impossible, since these
are user-supplied macros. The actually sound well-abbreviated to the
authors at the time they are defined. And at this time it is unclear
which ones will be used most.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/sTeX/issues/64>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------
