### ISSUE TITLE
numberit and locateit can only go together

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#75]
it seems that ```locateit``` only works if ```numberit``` is specified as well. Is this intended?

Is there a way to call them in one function? Probably not, since one is before and the other after. 

 What if we do not want to number?

**Comment by dginev** [comment]
As far as I remember you need to have hooks in both afterOpen and afterClose so that you can try to approximate the start and end locations for that XML element.

If you don't want to always number, you can probably splinter numberIt into two subroutines, one that does numbering and one that doesn't, and choose from the accordingly.

**Comment by dginev** [comment]
So, refactoring is possible, but you will always need to hook in both places for easy access to the location-holding objects.

However, this is Perl we are talking about. So you can make a new subroutine:
```perl
 sub locationHooks { (afterOpen=>\&numberIt,afterClose=>\&locateIt) }
 # And use it as:
 Tag('omdoc:imports',locationHooks());
```

Aliases are perfectly ok.

**Comment by kohlhase** [comment]
thanks for the clarification, I think then this is not worth the hassle (at the moment).
