### ISSUE TITLE
A question about string equality

### ISSUE THREAD

**Issue by La-Stravaganza** [KWARC/sTeX#87]
```latex
\documentclass{article}
\begin{document}
	
\def\a{abc}
\def\b{abc}
\def\c{\a}

\ifx\b\c
Equal
\else
Not Equal
\fi
\end{document}
```

will give me “Not Equal”, how can I get equal?

**Comment by dginev** [comment]
You should grab the TeX book from the IRC, it's a wealth for explaining this fine intricacies. Though by now StackExchange is also great:
http://tex.stackexchange.com/a/31656/78008

The trick you can do is to define ```\c``` via ```\edef``` so that you compare the fully expanded tokens. Here is an example:
http://latexml.mathweb.org/editor?tex=%0A%5Cdef%5Ca%7Babc%7D%0A%5Cdef%5Cb%7Babc%7D%0A%5Cedef%5Cc%7B%5Ca%7D%0A%0A%5Cifx%5Cb%5Cc%0AEqual%0A%5Celse%0ANot%20Equal%0A%5Cfi

**Comment by La-Stravaganza** [comment]
Thanks Deyan! TeXbook is already on my hand.
