### ISSUE TITLE
integrate the new path canonicalization into modules.sty (relative paths)

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#89]
We want to avoid duplicate loading of module signatures in sTeX (```modules.sty```). Currently in ```\@importmodule```, we test if we have seen the path already (the line with ```\IfStrEq```, and that does not really work with relative paths, which can be non-canonical). Actually, we cannot do relative paths at all at the moment (they are relative to the current file; we need to compose the load prefixes and normalize). I am not sure I have expressed myself clearly here, so just ask. 
Assigning to @La-Stravaganza

**Comment by La-Stravaganza** [comment]
Now I understand the whole loading procedure much more clearly, let  me take ``/path/to/localmh/MathHub/smglom/numbers/cube.tex`` as an  example for illustration.

In ``cube.tex``, it has this line of code:
```latex
\gimport[smglom/numberfields]{naturalnumbers}
```
then, after setting sort of things, parameters will be passed to:
```latex
\importmhmodule[repos=smglom/numberfields, ext=tex, path=naturalnumbers]{naturalnumbers}
```
then to:
```latex
\importmodule[load=path/to/localmh/smglom/numberfields/source/naturalnumbers, ext=tex, ...]{naturalnumbers}
```
and:
```latex
\@importmodule[path/to/localmh/smglom/numberfields/source/naturalnumbers]{naturalnumbers}{tex}
```
Under ``\@importmodule``, 
``\@load``will be set to ``path/to/localmh/smglom/numberfields/source/naturalnumbers``.
``\@path`` is set in more detailed way, generally is set as the first argument of \@importmodule.

Also, ``\mh@repos`` stores the directory for ``cube.tex``, which is ``smglom/numbers``.

So after I analyzed this thing, I didn't find an appropriate way to implement canonicalization. Mainly because, if I only use ``gimport`` as an interface for smglom, I have no way to know the first argument for ``gimport`` is an absolute path(under /path/to/localmh/MathHub) or a relative path(under /path/to/localmh/MathHub/smglom/numbers).

The canonicalization could be done if I write a new interface only for relative path, probably called ``grimport`` or something, then I can make a new if flag and do the suitable canonicalization. I am not sure this is the best way, if you have better idea, please tell me.

**Comment by kohlhase** [comment]
I think we want to leave ```\gimport``` and ```\importmhmodule``` alone for relative paths. They live quite happily with absolute paths. I should probably have specified this. 

So let us think about ```\importmodule[load=../../smglom/numberfields/source/naturalnumbers]```. 
and get this to work. The way I imgine this is that there is a local macro like ```\load@path@prefix``` that is initially (i.e. when TeX processing starts) empty and is updated to the new local directory with something like
```
\ddef\load@path@prefix{\@canonicalize{\load@path@prefix{smglom/numberfields/source}}}
``` 
when  ```\importmodule[load=../../smglom/numberfields/source/naturalnumbers]``` is processed. 
Then ```\@path``` and ```\@load```  can be set for ```\@importmodule```. 

Does this help?

**Comment by La-Stravaganza** [comment]
If I directly use ``\importmodule``, where can I get the path of current file?  If this part is solved, I could make a macro like ``\load@path@prefix`` and store the canonicalized path there. But still I am quite confused about how to change the existing logic of ``\@path`` and ``\@load``.

**Comment by kohlhase** [comment]
on top level (i.e. before the first ```\importmodule``` the current path is empty.

**Comment by La-Stravaganza** [comment]
So suppose we have a file ``/path/to/localmh/smglom/numbers/cube.tex`` and it wants to ``\importmodule[load=../../smglom/numberfields/source/naturalnumbers]``. How can I store ``smglom/numbers`` in ``\load@path@prefix``? I didn't figure out how you store address into ``\mh@currentrepos`` at the beginning.

**Comment by kohlhase** [comment]
No, you misunderstand (I think). ```modules,sty``` should initialize ```\load@path@prefix``` as empty with  ```\def\load@path@prefix{}```. When you run ```lmh pdf``` on ```.../cube.tex```, then ```\importmodule``` concatenates the existing (empty) prefix with the new path ```../../smglom/numberfields/source/``` giving the new prefix ```../../smglom/numberfields/source/```. Then if ```naturalnumbers.tex``` has ```\importmodule[load=../../foo/bar/source/foobar], ```\importmodules``` concatenates the existing prefix ``../../smglom/numberfields/source/``` with the new path ```../../foo/bar/source/foobar``` to become ```../../smglom/numberfields/source/../../foo/bar/source/foobar``` which is canonicalized as ```../../foo/bar/source/foobar```. Note that this is the correct prefix for ```foobar.tex``` as viewed from ```cube.tex```. 
Does this example help you?

**Comment by La-Stravaganza** [comment]
As far as I understand, the first file has a empty prefix, so for this file it must import something like ``\importmodule[load=path/to/localmh/MathHub/smglom/mv/source/equal]``. Am I right here? 

Then for ``equal.tex``, if it wants to import ``\importmodule[load=../../../sets/source/bijective]``, so the prefix for ``equal.tex`` is ``./../../sets/source/bijective``, and the actual loading path should be ``/path/to/localmh/MathHub/smglom/mv/source/equal/../../../sets/source/bijective`` , which is ``/path/to/localmh/MathHub/smglom/sets/source/bijective``right? Otherwise we have no way to load this file.

What confuses me is, the top interface ``gimport`` and ``importmhmodule`` use absolute path, then the loading path passed to ``importmodule`` must be canonical address. Could you tell me one situation that we could meet relative loading in ``importmodule``?  Since we really load something through ``\importmodule``, I must do something with the ``\importmodule@load`` macro, not just do stuff with prefix. For this purpose, I want to know how to get the current directory.

**Comment by kohlhase** [comment]
> Am I right here?

no. LaTeX should always start off with an empty prefix (since all files it loads are referenced from the currend directory), in particular, it can import ```equal.tex``` via a relative path. But this does not matter for our argument absolute paths are just a subset of relative paths, and the rest you seem to have understood. 

> Could you tell me one situation that we could meet relative loading in importmodule

NOTE I currently do not use ```\importmodule``` directly, since I host all my stuff on mathhub.info and therefore can work with absolute paths. 
But say you want to write an sTeX paper, using some clone of smglom. Then you use ```\importmodule``` directly. And that is what I want to help people do. 
does this help?

**Comment by La-Stravaganza** [comment]
Yes, this helps a lot.

**Comment by La-Stravaganza** [comment]
The logic of ``cpath`` now is fully correct. I implemented a new command sequence called ``rinput`` to support relative path inputs, which has been already documented in the manual.

**Comment by kohlhase** [comment]
I am afraid we misunderstood each other. I did not want to have a new macro ```\rinput```, but I wanted to allow ```\importmodule``` to take relative paths.

**Comment by kohlhase** [comment]
Oh, and ```\inputref``` as well.

**Comment by La-Stravaganza** [comment]
``\inputref`` now supports relative path.
 
I am not sure about what ``\mod@path`` is for, with absolute path something like ``/path/to/localmh/MikoMH/.../frontmatter`` will be assigned to ``\mod@path``. What should I do with ``\mod@path`` if it is relative path? 

Right now I do nothing, and it works, But I still concern about this.

**Comment by La-Stravaganza** [comment]
Please correct me if somewhere is wrong

My understanding of the mechanism of avoiding multiple loading for the same module:

<1> In ``\requiremodules`` macro, ``\mod@path`` and ``\mod@ext`` will be defined.
```latex
\newrobustcmd\requiremodules[2]{%
  \mod@showfalse%
  \@importingtrue% save state and ensure silence while reading sms
  \edef\mod@path{#1}%
  \edef\mod@ext{#2}% set up path/ext
  \input{#1.#2}%
}%
```
<2> In ``module`` environment, these two macros will be picked up. If these two macros have been defined, then define a global macro ``module@<name>@path``, as a flag.
```latex
\newenvironment{module}[1][]{%
  \begin{@module}[#1]%
  \ifcsundef{mod@id}{}{% only define if components are!
    \ifcsundef{mod@path}{}{\csxdef{module@\mod@id @path}{\mod@path}}%
    \ifcsundef{mod@ext}{}{\csxdef{module@\mod@id @ext}{\mod@ext}}%
  }%
  \module@heading% make the headings
}{%
  \end{@module}%
}%
```

<3> In ``@importmodule`` environment, check if ``module@<name>@path`` is defined, and avoid multiple loading.
```latex
\newrobustcmd\@importmodule[3][]{%
  {\@importingtrue% to shut up macros while in the group opened here
  \edef\@load{#1}%
  \ifx\@load\@empty%
    \relax%
  \else%
    \ifcsundef{module@#2@path}{%
      \requiremodules{#1}{#3}%
    }{%
      \edef\@path{\csname module@#2@path\endcsname}%
      \IfStrEq\@load\@path{% if the known path is the same as the requested one
        \relax% do nothing, it has already been loaded, else signal an error
	  }{%
        \PackageError{modules}
        {{Module Name Clash\MessageBreak
        A module with name #2 was already loaded under the path "\@path"\MessageBreak
        The imported path "\@load" is probably a different module with the\MessageBreak
        same name; this is dangerous -- not importing}%
        {Check whether the Module name is correct}}%
      }%
    }%
  \fi}%
  \activate@defs{#2}% activate the module
  \if@export\export@defs{#2}\fi% export the module
}%
```

Especially this line of code:
```latex
\IfStrEq\@load\@path{% if the known path is the same as the requested one
```
will check the equality, which means we have put the same address inside, no matter this macro is loaded by relative path or absolute path.

Currently something like ``/path/to/localmh/smglom/set/source/bijective`` is the value for ``\module@bijective@path``, but if module ``bijective`` is loaded by relative path, I have no way to get the absolute path for it, so I can't define ``\mod@path``, otherwise an error will be signaled.

**Comment by kohlhase** [comment]
this seems done.
