### ISSUE TITLE
preloading tikz and listings

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#91]
There has been a fix in Bruce's LaTeXML branch which (I hope) allows to preload all of listings.sty.ltxml and tikz.sty.ltxml with all their dependencies. This should speed up conversion by a large factor, so I had hoped that this would find its way into the KWARC branch, but we still seem to be re-loading the dependencies every time. 
@dginev could you please clarify? 

It seems that ```lmh``` still uses the generic ```stex-modules.opt``` profile, that should change as well.

**Comment by dginev** [comment]
You can preload listings with all its dependencies but not tikz. As long as you are using --preload, listings now auto-magically loads all language definition files, so that you never need to load anything during the actual conversion runs.

We need something similar for tikz, but preloading *all* of tikz will be rather slow. There are many libraries and each takes tens of seconds to load with LaTeXML.

**Comment by kohlhase** [comment]
In what way is ```tikz.sty``` so different from ```listings.sty```? Is it the libraries? 

But if I understand correctly, preloading the core tikz should be possible (i.e. all that is loaded by ```\usepackage{tikz}```). And then we need something for the libraries that are loaded with ```\usetikzlibrary``` they should be preloaded separately (if they are needed).

**Comment by dginev** [comment]
Well, tikz does a lot more than listings, and it is much larger, making it a lot slower to load. Also, the raw TeX loading is a much bigger component for tikz than it is for listings.

You can already do ```--preload=tikz.sty``` to get the core library, and it should be possible to do something like ```--preload='literal:\usetikzlibrary{foo}``` to get the libraries loaded on the side, but I haven't tried that.

**Comment by cmaeder** [comment]
@kohlhase can this be closed, too?

**Comment by kohlhase** [comment]
> @kohlhase can this be closed, too?

yes
